### ISSUE TITLE
Deselecting e.g. Oak Wood adds another Oakwood to list and removes one entry from loot

### ISSUE THREAD

**Issue by herkulessi** [Blechlawine/SnMInteractiveMap#1]
Deselecting one of the Categories entries adds another one of the same kind to the bottom of this catergories list and removes one from the other category.
Only tested on the Deployment bc I have no Idea how to start it.

**Comment by Blechlawine** [comment]
@herkulessi thanks for submitting the issue, it should be fixed in the upcoming version 1 release, which should take about 2 more weeks.
